version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    expose:
      - "80"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./server/data:/app/data
    environment:
      - PORT=8081
    ports:
      - "8081:8081"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  data:
